language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository

jdk:
- oraclejdk8

branches:
  except:
  - gh-pages

notifications:
  email: false

jobs:
  include:
  - stage: format
    name: Detekt
    script: "./detekt"
  - stage: test
    name: Lint
    script: "./gradlew lintRelease"
  - name: Unit Tests
    script: "./gradlew testReleaseUnitTest"

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
