language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - emulator
  # - extra-google-google_play_services
  # - extra-android-m2repository
  # - extra-android-support
  # - extra-google-m2repository

jdk:
- oraclejdk8

branches:
  except:
  - gh-pages

before_install:
# - export ANDROID_HOME=$HOME/sdk
# - export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/tools
# - ./setup_sdk.sh


notifications:
  email: false
# jobs:
#   include:
#     - stage: test
#       name: 'MvRx Unit Tests'
#       script: ./gradlew :mvrx:test
#     - name: 'MvRx Lint'
#       script: ./gradlew :mvrx:lint
#     - name: 'Sample App Unit Tests'
#       script: ./gradlew :sample:test
#     - name: 'Sample App Lint'
#       script: ./gradlew :sample:lint
#     - name: 'Instrumentation Tests'
#       script:
#       - ./start_emulator.sh
#       - ./test.sh

script:
- ./start_emulator.sh
- ./test.sh

sudo: false

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$TRAVIS_BUILD_DIR/build"
  - "$TRAVIS_BUILD_DIR/mvrx/build"
  - "$TRAVIS_BUILD_DIR/sample/build"
  - "$ANDROID_HOME"